development:
  adapter: postgresql
  encoding: unicode
  database: nabthat_dev
  host: localhost
  pool: 5
  username: postgres
  password: admin123
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: nthat1_pro
  host: localhost
  pool: 5
  username: nthat_user
  password: nabthat
  min_messages: warning

