development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: user
  database: development

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: user
  database: production
